name: Heroku-demo

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout successful message
      run: echo "Checkout successful"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Using Eclipse Temurin (OpenJDK distribution)

    - name: Build with Maven
      run: mvn clean install

    - name: Test connectivity to SonarQube server
      run: curl -v ${{ secrets.SONAR_URL }}
           echo "Connection successful"

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=heroku-demo
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_CRED }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
