name: Heroku-demo

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Checkout successful message
      run: echo "Checkout successful"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Using Eclipse Temurin (OpenJDK distribution)

    - name: Build with Maven
      run: mvn clean install
