name: Heroku-demo

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout successful message
      run: echo "Checkout successful"

    - name: Set up JDK 17
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '17'
        distribution: 'temurin' # Using Eclipse Temurin (OpenJDK distribution)

    - name: Build with Maven
      run: mvn clean install

    - name: SonarQube Scan
      run: mvn sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_CRED
